# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: hMRI Toolbox Documentation
site_author: hMRI Toolbox Developers
site_description: Documentation of the hMRI Toolbox

# Repository
repo_url: https://github.com/hMRI-group/hMRI-toolbox
repo_name: MRI-group/hMRI-toolbox
edit_uri: https://github.com/hMRI-group/hMRI-toolbox-docs/blob/main/docs/

# Copyright
copyright: Copyright &copy; 2012 - 2023 hMRI Toolbox Team and Collaborators

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/images/Logo_Dark_32x32@128x.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - Home: index.md
  - Information: information.md
  - Quick Start: quickstart.md
  - Docs:
      - Home: docs/index.md
      - Getting Started: docs/getStarted.md
      - Metadata Library: docs/metadataLibrary.md
      - Automatic Reorientation: docs/autoReorient.md
      - BIDS: docs/BIDS.md
      - Debug Metadata and Log Files: docs/debugMetadataAndLogFiles.md
      - Defaults and Customization: docs/defaultsAndCustomization.md
      - Help Scripts: docs/helpScripts.md
      - Hmri Demo Dataset: docs/hmriDemoDataset.md
      - Map Creation: docs/mapCreation.md
      - Processing: docs/processing.md
      - QUIQI: docs/QUIQI.md
      - References: docs/references.md
      - Releases: docs/releases.md
  - Development:
      - Home: development/index.md
      - Unit Testing: development/unit_tests.md
      - Releases: development/releases.md
      - Contributing: development/contribute.md
      - API Reference: development/api.md
  - Contact: contact.md
#  - API: API/api.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  #- mdx_truly_sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - toc:
      permalink: true

plugins:
  - macros
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "42.172vw"
      is_video: True
      video_autoplay: False
  - search:
      lang: en

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hMRI-group
    - icon: fontawesome/solid/comment
      link: https://matrix.to/#/#hMRI-toolbox:gitter.im
    - icon: mpg
      link: https://www.cbs.mpg.de/departments/neurophysics/software/hmri-toolbox

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
