# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: hMRI Toolbox Documentation
site_author: hMRI Toolbox Developers
site_description: Documentation of the hMRI Toolbox

# Repository
repo_url: https://github.com/hMRI-group/hMRI-toolbox
repo_name: MRI-group/hMRI-toolbox
edit_uri: https://github.com/hMRI-group/hMRI-toolbox-docs/blob/main/docs/

# Copyright
copyright: Copyright &copy; 2012 - 2023 hMRI Toolbox Team and Collaborators

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/images/Logo_Dark_32x32@128x.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - Home: index.md
  - Information: information.md
  - Quick Start: quickstart.md
  - Tutorials:
      - Home: tutorials/index.md
      - GetStarted: tutorials/GetStarted.md
      - MetadataLibrary: tutorials/MetadataLibrary.md
      - AutoReorient: tutorials/AutoReorient.md
      - BIDS: tutorials/BIDS.md
      - Contact: tutorials/Contact.md
      - Contribute: tutorials/Contribute.md
      - DebugMetadataAndLogFiles: tutorials/DebugMetadataAndLogFiles.md
      - DefaultsAndCustomization: tutorials/DefaultsAndCustomization.md
      - DevelopmentGuidelines: tutorials/DevelopmentGuidelines.md
      - HelpScripts: tutorials/HelpScripts.md
      - HmriDemoDataset: tutorials/HmriDemoDataset.md
      - MapCreation: tutorials/MapCreation.md
      - Processing: tutorials/Processing.md
      - QUIQI: tutorials/QUIQI.md
      - References: tutorials/References.md
      - Releases: tutorials/Releases.md
  - Development: development.md
  - API: API/api.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  #- mdx_truly_sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - toc:
      permalink: true

plugins:
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "42.172vw"
      is_video: True
      video_autoplay: False
  - bibtex:
      bib_file: "docs/assets/bib/hmri.bib"
  - search:
      lang: en

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hMRI-group
    - icon: fontawesome/solid/brain
      link: https://www.cbs.mpg.de/departments/neurophysics/software/hmri-toolbox

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
